stages:
  - build
  - test
  - deploy

install_and_build:
  stage: build
  image: node:latest
  script:
    - cd ./frontend && npm install
    - npm run build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

unit-test-job:
  stage: test
  image: node:latest
  script:
    - echo "Running Jest tests..."
    - cd frontend # Navigate to the front-end directory
    - npm install # Install dependencies
    - npm test # Run Jest tests
    - echo "Jest tests complete."

selenium-test-job:
  stage: test
  image: python:3.8
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium
  script:
    - echo "Running Selenium tests..."
    - pip install selenium webdriver-manager
    - python -m unittest discover -s frontend/__tests__ -p "acceptance-tests.py" -v
    - echo "Selenium tests complete."

postman_tests:
  stage: test
  image: postman/newman:latest
  dependencies:
    - install_and_build
  script:
    - newman run backend/app/postman_tests/parentaidatx_postman_collection.json --reporters cli,junit --reporter-junit-export results.xml
  artifacts:
    when: always
    paths:
      - results.xml
    reports:
      junit: results.xml
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

run_api_tests:
  stage: test
  image: python:3.10
  dependencies:
    - install_and_build
  before_script:
    - pip install -r backend/app/requirements.txt
    - export FLASK_TESTING=1  # Ensures tests don’t modify the real database
  script:
    - pytest backend/app/unit_tests/ --junitxml=results.xml
  artifacts:
    when: always
    paths:
      - results.xml
    reports:
      junit: results.xml
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

# deploy_to_ec2:
#   stage: deploy
#   image: alpine:latest
#   before_script:
#     - apk add --no-cache openssh
#   script:
#     - mkdir -p ~/.ssh
#     - echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_ed25519
#     - chmod 600 ~/.ssh/id_ed25519
#     - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
#     - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
#         cd /home/ubuntu/cs373-spring-2025-group-17 &&
#         git pull origin main &&
#         docker stop parentaid-container || true &&
#         docker rm parentaid-container || true &&
#         docker build -t parentaid-backend ./backend/app &&
#         docker run -d --name parentaid-container -p 5000:5000 parentaid-backend
#       '
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
#       when: always


deploy_to_amplify:
  stage: deploy
  image: node:latest
  dependencies:
    - unit-test-job
    - selenium-test-job
  script:
    - echo "Deploying to Amplify"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
