stages:
  - build
  - test
  - deploy

install_and_build:
  stage: build
  image: node:latest
  script:
    - cd ./frontend && npm install
    - npm run build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

run_tests:
  stage: test
  image: node:latest
  dependencies:
    - install_and_build
  before_script:
    - cd ./frontend
    - npm install # Ensure dependencies are installed
  script:
    # Run Jest tests for frontend (React)
    - npm test -- --coverage
    # Run Selenium tests for acceptance testing (Python)
    - pip install selenium webdriver-manager unittest-xml-reporting
    - python -m unittest discover -s ./frontend/__tests__ -p "*.py"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

deploy_to_amplify:
  stage: deploy
  image: node:latest
  dependencies:
    - run_tests
  script:
    - echo "Deploying to Amplify"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
